// Package e2e provides user-facing scenario-based E2E test infrastructure.
package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestParseScenarios_AllFields_Parsed verifies that every field in a scenario
// block is correctly deserialized into the Scenario struct.
func TestParseScenarios_AllFields_Parsed(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — myproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: mybinary
## Build: go build -o mybinary .

### S3: full-fields — All fields present
- **Command**: ` + "`mybinary init --name test`" + `
- **Precondition**: binary built, config exists
- **Env**: MY_KEY=myval
- **Expect**: exit 0
- **Verify**: exit_code(0), stdout_contains("initialized")
- **Depends**: S1
- **Status**: active
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 1)

	s := set.Scenarios[0]
	assert.Equal(t, 3, s.Number)
	assert.Equal(t, "full-fields", s.ID)
	assert.Equal(t, "All fields present", s.Description)
	assert.Contains(t, s.Command, "mybinary init")
	assert.Equal(t, "binary built, config exists", s.Precondition)
	assert.Equal(t, "MY_KEY=myval", s.Env)
	assert.Equal(t, "exit 0", s.Expect)
	assert.Len(t, s.Verify, 2)
	assert.Equal(t, "S1", s.Depends)
	assert.Equal(t, "active", s.Status)
}

// TestParseScenarios_MetadataFields verifies ProjectType, Binary, Build are parsed.
func TestParseScenarios_MetadataFields(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — ProjectAlpha

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: API
## Binary: apiserver
## Build: make build
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	assert.Equal(t, "ProjectAlpha", set.ProjectName)
	assert.Equal(t, "API", set.ProjectType)
	assert.Equal(t, "apiserver", set.Binary)
	assert.Equal(t, "make build", set.Build)
	assert.Empty(t, set.Scenarios)
}

// TestParseScenarios_MultipleScenarios verifies that multiple scenario blocks
// are all parsed correctly.
func TestParseScenarios_MultipleScenarios(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — multi

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build .

### S1: alpha — First scenario
- **Command**: ` + "`auto alpha`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active

### S2: beta — Second scenario
- **Command**: ` + "`auto beta`" + `
- **Precondition**: alpha done
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: S1
- **Status**: deprecated
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 2)
	assert.Equal(t, "alpha", set.Scenarios[0].ID)
	assert.Equal(t, "beta", set.Scenarios[1].ID)
	assert.Equal(t, "deprecated", set.Scenarios[1].Status)
	assert.Equal(t, "S1", set.Scenarios[1].Depends)
}

// TestRenderScenarios_EmptySet verifies that RenderScenarios handles an empty
// ScenarioSet without panicking, producing a valid header.
func TestRenderScenarios_EmptySet(t *testing.T) {
	t.Parallel()

	set := &ScenarioSet{
		ProjectName: "empty-project",
		ProjectType: "CLI",
		Binary:      "N/A",
		Build:       "N/A",
	}

	out, err := RenderScenarios(set)
	require.NoError(t, err)
	assert.Contains(t, string(out), "# E2E Scenarios — empty-project")
	assert.Contains(t, string(out), "## Project Type: CLI")
}

// TestParseScenarios_MultiBuildLine_PopulatesBuilds verifies that a multi-build
// Build line is parsed into both the raw Build string and the Builds slice.
func TestParseScenarios_MultiBuildLine_PopulatesBuilds(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — multiproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build ./cmd/auto/ (ADK), go build ./cmd/server/ (Backend)
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	assert.Equal(t, "go build ./cmd/auto/ (ADK), go build ./cmd/server/ (Backend)", set.Build)
	require.Len(t, set.Builds, 2)
	assert.Equal(t, "ADK", set.Builds[0].Label)
	assert.Equal(t, "go build ./cmd/auto/", set.Builds[0].Command)
	assert.Equal(t, "autopus-adk", set.Builds[0].SubmodulePath)
	assert.Equal(t, "Backend", set.Builds[1].Label)
	assert.Equal(t, "go build ./cmd/server/", set.Builds[1].Command)
}

// TestParseScenarios_SingleBuildLine_PopulatesBuilds verifies that a single
// build command without label populates Builds with one unlabeled entry.
func TestParseScenarios_SingleBuildLine_PopulatesBuilds(t *testing.T) {
	t.Parallel()

	set, err := ParseScenarios([]byte(sampleMarkdown))
	require.NoError(t, err)
	require.Len(t, set.Builds, 1)
	assert.Equal(t, "go build -o auto ./cmd/auto", set.Builds[0].Command)
	assert.Empty(t, set.Builds[0].Label)
}

// TestParseScenarios_EmptyBuildLine_NilBuilds verifies that an empty Build
// line results in nil Builds slice.
func TestParseScenarios_EmptyBuildLine_NilBuilds(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — nobuild

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: N/A
## Build:
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	assert.Nil(t, set.Builds)
}

// TestRenderParseRoundTrip_MultiBuild_PreservesBuilds verifies that a
// ScenarioSet with multi-build entries survives render → parse round-trip.
func TestRenderParseRoundTrip_MultiBuild_PreservesBuilds(t *testing.T) {
	t.Parallel()

	original := &ScenarioSet{
		ProjectName: "roundtrip",
		ProjectType: "CLI",
		Binary:      "auto",
		Builds: []BuildEntry{
			{Command: "go build ./cmd/auto/", Label: "ADK", SubmodulePath: "autopus-adk"},
			{Command: "npm run build", Label: "Frontend", SubmodulePath: "Autopus/frontend"},
		},
	}

	rendered, err := RenderScenarios(original)
	require.NoError(t, err)

	parsed, err := ParseScenarios(rendered)
	require.NoError(t, err)
	require.Len(t, parsed.Builds, 2)
	assert.Equal(t, "ADK", parsed.Builds[0].Label)
	assert.Equal(t, "go build ./cmd/auto/", parsed.Builds[0].Command)
	assert.Equal(t, "Frontend", parsed.Builds[1].Label)
	assert.Equal(t, "npm run build", parsed.Builds[1].Command)
}

// TestParseScenarios_DeprecatedStatus verifies that deprecated status is parsed correctly.
func TestParseScenarios_DeprecatedStatus(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — dep-test

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: N/A

### S1: old-cmd — Old command
- **Command**: ` + "`auto old-cmd`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: deprecated
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 1)
	assert.Equal(t, "deprecated", set.Scenarios[0].Status)
}
