// Package e2e provides user-facing scenario-based E2E test infrastructure.
package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// sampleMarkdown is a minimal valid scenarios.md fixture.
const sampleMarkdown = `# E2E Scenarios — testproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build -o auto ./cmd/auto

### S1: init — Initialize project
- **Command**: ` + "`auto init`" + `
- **Precondition**: binary built
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0), stdout_contains("initialized")
- **Depends**: N/A
- **Status**: active

### S2: doctor — Run diagnostics
- **Command**: ` + "`auto doctor`" + `
- **Precondition**: project initialized
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: S1
- **Status**: active
`

// TestParseScenarios_ValidMarkdown_ReturnsScenarioSet verifies that a well-formed
// scenarios.md is parsed into a ScenarioSet with the expected number of scenarios.
// S16: round-trip identity.
func TestParseScenarios_ValidMarkdown_ReturnsScenarioSet(t *testing.T) {
	t.Parallel()

	// Given: a valid scenarios.md content
	// When: ParseScenarios is called
	set, err := ParseScenarios([]byte(sampleMarkdown))

	// Then: no error and two scenarios are returned with Builds populated
	require.NoError(t, err)
	require.NotNil(t, set)
	assert.Len(t, set.Scenarios, 2)
	require.Len(t, set.Builds, 1)
	assert.Equal(t, "go build -o auto ./cmd/auto", set.Builds[0].Command)
}

// TestRenderScenarios_FromScenarioSet_MatchesOriginal verifies that rendering
// a parsed ScenarioSet produces output identical to the original input.
// S16: round-trip identity — parse -> render must be equal.
func TestRenderScenarios_FromScenarioSet_MatchesOriginal(t *testing.T) {
	t.Parallel()

	// Given: parsed scenarios
	set, err := ParseScenarios([]byte(sampleMarkdown))
	require.NoError(t, err)

	// When: rendered back to markdown
	got, err := RenderScenarios(set)

	// Then: output matches original
	require.NoError(t, err)
	assert.Equal(t, sampleMarkdown, string(got))
}

// TestParseScenarios_SpecialCharacters_PreservedInValues verifies that pipe and
// backtick characters inside field values survive the parse cycle unchanged.
// S18: special character preservation.
func TestParseScenarios_SpecialCharacters_PreservedInValues(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — testproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build -o auto ./cmd/auto

### S1: pipe-test — Pipe and backtick in values
- **Command**: ` + "`auto doctor | grep ok`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0), stdout_contains("ok")
- **Depends**: N/A
- **Status**: active
`

	// Given: scenarios.md with pipe and backtick characters
	// When: parsed
	set, err := ParseScenarios([]byte(input))

	// Then: special characters are preserved in Command field
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 1)
	assert.Contains(t, set.Scenarios[0].Command, "|")
	assert.Contains(t, set.Scenarios[0].Command, "`")
}

// TestParseScenarios_SectionHeader_AssignedToScenarios verifies that section
// headers (## ... Scenarios) are propagated to the Scenario.Section field.
func TestParseScenarios_SectionHeader_AssignedToScenarios(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — sectioned

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build ./cmd/auto/ (ADK), npm run build (Frontend)

## ADK CLI Scenarios

### S1: init — Initialize project
- **Command**: ` + "`auto init`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active

## Frontend Scenarios

### S2: build-ui — Build frontend
- **Command**: ` + "`npm run build`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 2)
	assert.Equal(t, "ADK CLI Scenarios", set.Scenarios[0].Section)
	assert.Equal(t, "Frontend Scenarios", set.Scenarios[1].Section)

	// Builds should also be populated
	require.Len(t, set.Builds, 2)
	assert.Equal(t, "ADK", set.Builds[0].Label)
	assert.Equal(t, "Frontend", set.Builds[1].Label)
}

// TestParseScenarios_EmptyFile_ReturnsEmptySet verifies that an empty or
// header-only file returns a ScenarioSet with zero scenarios without error.
func TestParseScenarios_EmptyFile_ReturnsEmptySet(t *testing.T) {
	t.Parallel()

	// Given: an empty byte slice
	// When: parsed
	set, err := ParseScenarios([]byte(""))

	// Then: empty set is returned without error
	require.NoError(t, err)
	assert.Empty(t, set.Scenarios)
}

// TestParseScenarios_CustomPrefix_Preserved verifies that scenarios whose ID
// carries the "custom-" prefix are preserved unchanged during sync.
// R3: manual edit preservation.
func TestParseScenarios_CustomPrefix_Preserved(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — testproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build -o auto ./cmd/auto

### S1: custom-smoke — Manual smoke test
- **Command**: ` + "`auto version`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active
`

	// Given: a scenario with "custom-" prefix in its ID
	// When: parsed
	set, err := ParseScenarios([]byte(input))

	// Then: scenario is present and ID retains the "custom-" prefix
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 1)
	assert.Equal(t, "custom-smoke", set.Scenarios[0].ID)
}
