// Package e2e provides user-facing scenario-based E2E test infrastructure.
package e2e

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// Scenario represents a single E2E test scenario.
type Scenario struct {
	Number       int      // S{N}
	ID           string   // unique identifier (e.g., "init", "doctor", "custom-mytest")
	Description  string   // short description
	Command      string   // command to execute
	Precondition string   // comma-separated preconditions
	Env          string   // KEY=value pairs or "N/A"
	Expect       string   // expected result
	Verify       []string // verification primitives
	Depends      string   // dependency (e.g., "S1" or "N/A")
	Status       string   // active | deprecated | skip
}

// ScenarioSet represents a complete scenarios.md document.
type ScenarioSet struct {
	ProjectName string
	ProjectType string // CLI | API | Frontend | Library
	Binary      string
	Build       string
	Scenarios   []Scenario
}

// @AX:NOTE [AUTO] @AX:REASON: magic constants — these regex patterns define the scenarios.md wire format; changing them breaks parse/render symmetry
var (
	reTitle       = regexp.MustCompile(`^# E2E Scenarios — (.+)$`)
	reProjectType = regexp.MustCompile(`^## Project Type: (.+)$`)
	reBinary      = regexp.MustCompile(`^## Binary: (.+)$`)
	reBuild       = regexp.MustCompile(`^## Build: (.+)$`)
	reScenHeader  = regexp.MustCompile(`^### S(\d+): ([^—]+) — (.+)$`)
	reField       = regexp.MustCompile(`^- \*\*([^*]+)\*\*: (.*)$`)
)

// @AX:NOTE [AUTO] @AX:REASON: public API boundary — sole entry point for scenarios.md deserialization; fan_in=1 (internal/cli/test.go)
// ParseScenarios parses scenarios.md content into a ScenarioSet.
func ParseScenarios(content []byte) (*ScenarioSet, error) {
	set := &ScenarioSet{}
	lines := strings.Split(string(content), "\n")

	var current *Scenario
	for _, line := range lines {
		if m := reTitle.FindStringSubmatch(line); m != nil {
			set.ProjectName = m[1]
			continue
		}
		if m := reProjectType.FindStringSubmatch(line); m != nil {
			set.ProjectType = m[1]
			continue
		}
		if m := reBinary.FindStringSubmatch(line); m != nil {
			set.Binary = m[1]
			continue
		}
		if m := reBuild.FindStringSubmatch(line); m != nil {
			set.Build = m[1]
			continue
		}
		if m := reScenHeader.FindStringSubmatch(line); m != nil {
			if current != nil {
				set.Scenarios = append(set.Scenarios, *current)
			}
			n, _ := strconv.Atoi(m[1])
			current = &Scenario{
				Number:      n,
				ID:          strings.TrimSpace(m[2]),
				Description: strings.TrimSpace(m[3]),
			}
			continue
		}
		if current == nil {
			continue
		}
		if m := reField.FindStringSubmatch(line); m != nil {
			key, val := m[1], m[2]
			switch key {
			case "Command":
				// preserve value as-is including surrounding backticks
				current.Command = val
			case "Precondition":
				current.Precondition = val
			case "Env":
				current.Env = val
			case "Expect":
				current.Expect = val
			case "Verify":
				parts := strings.Split(val, ", ")
				current.Verify = parts
			case "Depends":
				current.Depends = val
			case "Status":
				current.Status = val
			}
		}
	}
	if current != nil {
		set.Scenarios = append(set.Scenarios, *current)
	}
	return set, nil
}

// @AX:NOTE [AUTO] @AX:REASON: public API boundary — sole serializer for scenarios.md; parse/render must remain symmetric; fan_in=1 (pkg/setup/scenarios.go)
// RenderScenarios renders a ScenarioSet back to scenarios.md markdown.
func RenderScenarios(set *ScenarioSet) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# E2E Scenarios — %s\n", set.ProjectName)
	buf.WriteString("\n")
	buf.WriteString("> Auto-generated by `/auto setup`. Updated by `/auto sync`.\n")
	buf.WriteString("\n")
	fmt.Fprintf(&buf, "## Project Type: %s\n", set.ProjectType)
	fmt.Fprintf(&buf, "## Binary: %s\n", set.Binary)
	fmt.Fprintf(&buf, "## Build: %s\n", set.Build)

	for _, s := range set.Scenarios {
		buf.WriteString("\n")
		fmt.Fprintf(&buf, "### S%d: %s — %s\n", s.Number, s.ID, s.Description)
		fmt.Fprintf(&buf, "- **Command**: %s\n", s.Command)
		fmt.Fprintf(&buf, "- **Precondition**: %s\n", s.Precondition)
		fmt.Fprintf(&buf, "- **Env**: %s\n", s.Env)
		fmt.Fprintf(&buf, "- **Expect**: %s\n", s.Expect)
		fmt.Fprintf(&buf, "- **Verify**: %s\n", strings.Join(s.Verify, ", "))
		fmt.Fprintf(&buf, "- **Depends**: %s\n", s.Depends)
		fmt.Fprintf(&buf, "- **Status**: %s\n", s.Status)
	}

	return buf.Bytes(), nil
}
