// Package cli는 init 커맨드를 구현한다.
package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/insajin/autopus-adk/internal/cli/tui"
	"github.com/insajin/autopus-adk/pkg/config"
	"github.com/insajin/autopus-adk/pkg/detect"
)

// @AX:NOTE [AUTO]: gitignorePatterns must match the files generated by each platform adapter
// gitignorePatterns는 autopus 관련 .gitignore 패턴 목록이다.
var gitignorePatterns = []string{
	".claude/rules/autopus/",
	".claude/skills/autopus/",
	".claude/commands/auto.md",
	".claude/agents/autopus/",
	".codex/skills/",
	".gemini/skills/autopus/",
	".agents/skills/",
	".autopus/",
	".mcp.json",
}

func newInitCmd() *cobra.Command {
	var (
		dir          string
		project      string
		platforms    string
		quality      string
		noReviewGate bool
		yes          bool
	)

	// @AX:WARN [AUTO]: RunE closure captures mutable flag vars — do not add goroutines inside RunE
	// @AX:REASON: quality, noReviewGate, yes are captured by reference; concurrent access would race
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize autopus harness in the current project",
		Long:  "코딩 CLI에 Autopus 하네스를 설치합니다. autopus.yaml을 생성하고 플랫폼 파일을 설치합니다.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if dir == "" {
				var err error
				dir, err = os.Getwd()
				if err != nil {
					return fmt.Errorf("현재 디렉터리를 가져올 수 없음: %w", err)
				}
			}

			mode := config.ModeFull
			if project == "" {
				project = filepath.Base(dir)
			}

			var platformList []string
			if platforms != "" {
				for _, p := range strings.Split(platforms, ",") {
					p = strings.TrimSpace(p)
					if p != "" {
						platformList = append(platformList, p)
					}
				}
			}
			if len(platformList) == 0 {
				platformList = []string{"claude-code"}
			}

			cfg := config.DefaultFullConfig(project)
			cfg.Platforms = platformList

			// Detect and set stack and framework for stack-aware rule generation.
			if stack, err := detect.DetectStack(dir); err == nil && stack != "" {
				cfg.Stack = stack
			}
			if fw, err := detect.DetectFramework(dir); err == nil && fw != nil {
				cfg.Framework = fw.Name
			}

			out := cmd.OutOrStdout()
			tui.BannerWithInfo(out, project, "init")

			// Detect orchestra providers for wizard and review gate.
			providers := detect.DetectOrchestraProviders()
			var providerNames []string
			for _, p := range providers {
				if p.Installed {
					providerNames = append(providerNames, p.Name)
				}
			}

			// Step 1: Configuration Wizard
			tui.Step(out, 1, 4, "Configuration Wizard")
			if !yes && isStdinTTY() {
				result, err := tui.RunInitWizard(tui.InitWizardOpts{
					Quality:      quality,
					NoReviewGate: noReviewGate,
					Platforms:    platformList,
					Accessible:   false,
					Providers:    providerNames,
				})
				if err != nil {
					return fmt.Errorf("wizard failed: %w", err)
				}
				if result.Cancelled {
					fmt.Fprintln(out, "  init cancelled.")
					return nil
				}
				// Apply wizard results to config.
				cfg.Language.Comments = result.CommentsLang
				cfg.Language.Commits = result.CommitsLang
				cfg.Language.AIResponses = result.AILang
				cfg.Quality.Default = result.Quality
				cfg.Spec.ReviewGate.Enabled = result.ReviewGate
				if result.ReviewGate {
					cfg.Spec.ReviewGate.Providers = providerNames
				}
				if result.Methodology == "tdd" {
					cfg.Methodology.Mode = "tdd"
					cfg.Methodology.Enforce = true
				} else {
					cfg.Methodology.Mode = "none"
					cfg.Methodology.Enforce = false
				}
			} else {
				// Non-interactive: apply flags or defaults.
				if quality != "" {
					cfg.Quality.Default = quality
				}
				if noReviewGate {
					cfg.Spec.ReviewGate.Enabled = false
				} else {
					cfg.Spec.ReviewGate.Providers = providerNames
					if len(providerNames) < 2 {
						cfg.Spec.ReviewGate.Enabled = false
					}
				}
			}

			// Save config after all prompts.
			if err := config.Save(dir, cfg); err != nil {
				return fmt.Errorf("autopus.yaml 저장 실패: %w", err)
			}

			// Step 2: Platform Files
			tui.Step(out, 2, 4, "Platform Files")
			ctx := context.Background()
			if err := generatePlatformFiles(ctx, dir, cfg, cmd); err != nil {
				return err
			}

			if err := generateDefaultConstraints(dir, out); err != nil {
				tui.Warnf(out, "constraints.yaml 생성 실패: %v", err)
			}

			// Step 3: Gitignore
			tui.Step(out, 3, 4, "Gitignore")
			if err := updateGitignore(dir); err != nil {
				return fmt.Errorf(".gitignore 업데이트 실패: %w", err)
			}

			warnParentRuleConflicts(cmd, dir, cfg)

			// Step 4: Summary
			tui.Step(out, 4, 4, "Summary")
			tui.SummaryTable(out, []tui.SummaryRow{
				{Key: "Quality", Value: cfg.Quality.Default},
				{Key: "Review Gate", Value: fmt.Sprintf("%v (%d providers)", cfg.Spec.ReviewGate.Enabled, len(cfg.Spec.ReviewGate.Providers))},
				{Key: "Methodology", Value: cfg.Methodology.Mode},
				{Key: "Platforms", Value: strings.Join(cfg.Platforms, ", ")},
				{Key: "Language", Value: fmt.Sprintf("comments=%s, commits=%s, ai=%s", cfg.Language.Comments, cfg.Language.Commits, cfg.Language.AIResponses)},
			})
			tui.Info(out, "Next: run 'auto doctor' to verify installation")
			tui.Successf(out, "Autopus harness initialized (%s mode)", mode)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", "", "프로젝트 루트 디렉터리 (기본값: 현재 디렉터리)")
	cmd.Flags().StringVar(&project, "project", "", "프로젝트 이름")
	cmd.Flags().StringVar(&platforms, "platforms", "", "설치할 플랫폼 목록 (쉼표 구분, 예: claude-code,codex)")
	cmd.Flags().StringVar(&quality, "quality", "", "Quality mode preset (ultra/balanced)")
	cmd.Flags().BoolVar(&noReviewGate, "no-review-gate", false, "Disable review gate")
	cmd.Flags().BoolVar(&yes, "yes", false, "Non-interactive mode (use defaults)")

	return cmd
}
