package cli

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// scenariosWithDeprecated is a scenarios.md with mixed active/deprecated scenarios.
const scenariosWithDeprecated = `# E2E Scenarios — testproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build:

### S1: echo-test — Echo command
- **Command**: ` + "`echo hello`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active

### S2: old-cmd — Deprecated command
- **Command**: ` + "`auto old`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: deprecated
`

// scenariosEmptyBlocks has header metadata only, no scenario blocks.
const scenariosEmptyBlocks = `# E2E Scenarios — emptyproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: N/A
## Build:
`

// TestTestRunCmd_DeprecatedScenarios_Skipped verifies that deprecated scenarios
// are not executed (only active ones count).
func TestTestRunCmd_DeprecatedScenarios_Skipped(t *testing.T) {
	t.Parallel()

	// Given: scenarios.md with one active and one deprecated scenario
	dir := t.TempDir()
	writeScenariosFile(t, dir, scenariosWithDeprecated)

	// When: "auto test run" is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir})
	err := cmd.Execute()

	// Then: command succeeds (deprecated scenario not counted as failure)
	require.NoError(t, err)
	// Summary line should show 1 run (not 2)
	assert.Contains(t, out.String(), "1/1")
}

// TestTestRunCmd_EmptyScenarioBlocks_NoScenariosMessage verifies that a
// scenarios.md with only header and no scenario blocks shows "no scenarios".
func TestTestRunCmd_EmptyScenarioBlocks_NoScenariosMessage(t *testing.T) {
	t.Parallel()

	// Given: scenarios.md with no scenario blocks
	dir := t.TempDir()
	writeScenariosFile(t, dir, scenariosEmptyBlocks)

	// When: "auto test run" is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir})
	err := cmd.Execute()

	// Then: no error and warning message about no scenarios
	require.NoError(t, err)
	assert.Contains(t, out.String(), "no scenarios")
}

// TestTestRunCmd_ScenarioIDFilter_RunsOnlyMatching verifies that --scenario
// flag filters execution to only the specified scenario ID.
func TestTestRunCmd_ScenarioIDFilter_RunsOnlyMatching(t *testing.T) {
	t.Parallel()

	// Given: scenarios.md with two active scenarios
	content := `# E2E Scenarios — filtertest

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: N/A
## Build:

### S1: alpha — Alpha command
- **Command**: ` + "`echo alpha`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active

### S2: beta — Beta command
- **Command**: ` + "`echo beta`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active
`
	dir := t.TempDir()
	writeScenariosFile(t, dir, content)

	// When: "auto test run --scenario alpha" is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--scenario", "alpha"})
	err := cmd.Execute()

	// Then: only alpha runs — summary shows 1/1
	require.NoError(t, err)
	assert.Contains(t, out.String(), "1/1")
}

// TestTestRunCmd_VerboseOutput_ShowsStdout verifies that --verbose flag
// outputs stdout content for each scenario.
func TestTestRunCmd_VerboseOutput_ShowsStdout(t *testing.T) {
	t.Parallel()

	// Given: scenarios.md with a command that produces stdout
	content := `# E2E Scenarios — verbosetest

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: N/A
## Build:

### S1: verbose-echo — Echo command
- **Command**: ` + "`echo verbose_output_marker`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active
`
	dir := t.TempDir()
	writeScenariosFile(t, dir, content)

	// When: "auto test run --verbose" is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--verbose"})
	err := cmd.Execute()

	// Then: stdout contains verbose output marker
	require.NoError(t, err)
	assert.Contains(t, out.String(), "verbose_output_marker")
}

// TestTestRunCmd_FailingScenario_ReturnsError verifies that a FAIL scenario
// causes the command to return a non-nil error.
func TestTestRunCmd_FailingScenario_ReturnsError(t *testing.T) {
	t.Parallel()

	// Given: a scenario that always fails (exit 1, expecting exit 0)
	content := `# E2E Scenarios — failtest

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: N/A
## Build:

### S1: fail-always — Always failing command
- **Command**: ` + "`sh -c 'exit 1'`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active
`
	dir := t.TempDir()
	writeScenariosFile(t, dir, content)

	// When: "auto test run" is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir})
	err := cmd.Execute()

	// Then: command returns an error indicating failure
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "failed")
}

// TestTestRunCmd_JSONNoScenarios_EmptyResults verifies that --json with no
// scenarios returns JSON with empty results array.
func TestTestRunCmd_JSONNoScenarios_EmptyResults(t *testing.T) {
	t.Parallel()

	// Given: project with no scenarios.md at all
	dir := t.TempDir()

	// When: "auto test run --json" is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--json"})
	err := cmd.Execute()

	// Then: no error, empty JSON results
	require.NoError(t, err)
	assert.Contains(t, out.String(), `"results"`)
}
