package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// sampleScenariosContent is a minimal scenarios.md for CLI tests.
const sampleScenariosContent = `# E2E Scenarios — testproject

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto

### S1: echo-test — Echo command
- **Command**: ` + "`echo hello`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0), stdout_contains("hello")
- **Depends**: N/A
- **Status**: active
`

// writeScenariosFile creates .autopus/project/scenarios.md in projectDir.
func writeScenariosFile(t *testing.T, projectDir, content string) {
	t.Helper()
	dir := filepath.Join(projectDir, ".autopus", "project")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "scenarios.md"), []byte(content), 0o644))
}

// TestTestRunCmd_ValidProject_Succeeds verifies that "auto test run" completes
// without error when a valid project with scenarios is provided.
func TestTestRunCmd_ValidProject_Succeeds(t *testing.T) {
	t.Parallel()

	// Given: a project directory with a valid scenarios.md
	dir := t.TempDir()
	writeScenariosFile(t, dir, sampleScenariosContent)

	// When: the auto test command is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir})
	err := cmd.Execute()

	// Then: command exits without error
	require.NoError(t, err)
}

// TestTestRunCmd_NoScenarios_ShowsWarning verifies that "auto test run" outputs
// a warning when no scenarios.md exists in the project directory.
func TestTestRunCmd_NoScenarios_ShowsWarning(t *testing.T) {
	t.Parallel()

	// Given: a project directory with no scenarios.md
	dir := t.TempDir()

	// When: the auto test command is executed
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir})
	err := cmd.Execute()

	// Then: no fatal error but output contains a warning about no scenarios
	require.NoError(t, err)
	assert.Contains(t, out.String(), "no scenarios")
}

// TestTestRunCmd_JSONOutput_FormatsCorrectly verifies that "auto test run --json"
// produces valid JSON with a "results" key containing scenario outcomes.
func TestTestRunCmd_JSONOutput_FormatsCorrectly(t *testing.T) {
	t.Parallel()

	// Given: a project directory with scenarios
	dir := t.TempDir()
	writeScenariosFile(t, dir, sampleScenariosContent)

	// When: the auto test command is executed with --json flag
	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--json"})
	err := cmd.Execute()

	// Then: output is valid JSON containing "results"
	require.NoError(t, err)
	var result map[string]interface{}
	parseErr := json.Unmarshal(out.Bytes(), &result)
	require.NoError(t, parseErr, "output should be valid JSON")
	assert.Contains(t, result, "results", "JSON output should have 'results' key")
}
