package sigmap

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// MaxLines is the hard limit for rendered Markdown output.
const MaxLines = 500

// Render converts a SignatureMap to Markdown format, respecting the line limit.
// If the full render exceeds MaxLines, packages are filtered by fan-in (descending),
// with depth as a tiebreaker (shallower first).
func Render(sm *SignatureMap) string {
	header := buildHeader(sm.ModulePath)
	packages := sm.Packages

	full := buildBody(header, packages, "")
	if countLines(full) <= MaxLines {
		return full
	}

	// Header lines consume part of the budget.
	headerLines := countLines(header)
	footerLines := 1 // one line for the filtered footer
	budget := MaxLines - headerLines - footerLines

	selected := filterByFanIn(packages, budget)
	omitted := len(packages) - len(selected)
	footer := fmt.Sprintf("<!-- Filtered: %d packages omitted (low fan-in) -->", omitted)

	return buildBody(header, selected, footer)
}

// buildHeader renders the top-level Markdown header section.
func buildHeader(modulePath string) string {
	return fmt.Sprintf(
		"# Signature Map\n\n> Auto-generated by `auto setup`. Do not edit manually.\n\nModule: `%s`\n",
		modulePath,
	)
}

// buildBody assembles the full Markdown document from header, package sections, and footer.
func buildBody(header string, packages []Package, footer string) string {
	var sb strings.Builder
	sb.WriteString(header)
	for i := range packages {
		sb.WriteString("\n")
		sb.WriteString(renderPackage(&packages[i]))
	}
	if footer != "" {
		sb.WriteString("\n")
		sb.WriteString(footer)
		sb.WriteString("\n")
	}
	return sb.String()
}

// renderPackage renders a single package section as Markdown.
func renderPackage(pkg *Package) string {
	var sb strings.Builder
	sb.WriteString("## ")
	sb.WriteString(pkg.Path)
	sb.WriteString("\n")
	for i := range pkg.Signatures {
		sb.WriteString("\n")
		sb.WriteString(formatSignature(&pkg.Signatures[i]))
		sb.WriteString("\n")
	}
	return sb.String()
}

// formatSignature formats one Signature as a Markdown list item.
func formatSignature(sig *Signature) string {
	var code string
	switch sig.Kind {
	case "method":
		code = fmt.Sprintf("func %s %s%s%s", sig.Receiver, sig.Name, sig.TypeParams, sig.Params)
		if sig.Returns != "" {
			code += " " + sig.Returns
		}
	case "type":
		code = fmt.Sprintf("type %s struct", sig.Name)
		if sig.TypeParams != "" {
			code = fmt.Sprintf("type %s%s struct", sig.Name, sig.TypeParams)
		}
	case "interface":
		code = fmt.Sprintf("interface %s", sig.Name)
	default: // "func"
		code = fmt.Sprintf("func %s%s%s", sig.Name, sig.TypeParams, sig.Params)
		if sig.Returns != "" {
			code += " " + sig.Returns
		}
	}

	if sig.Doc != "" {
		return fmt.Sprintf("- `%s` — %s", code, sig.Doc)
	}
	return fmt.Sprintf("- `%s`", code)
}

// countLines returns the number of lines in a string.
// An empty string returns 0.
func countLines(s string) int {
	if s == "" {
		return 0
	}
	return strings.Count(s, "\n") + 1
}

// filterByFanIn sorts packages by FanIn desc, Depth asc, then greedily selects
// packages until adding the next would exceed maxLines.
func filterByFanIn(packages []Package, maxLines int) []Package {
	sorted := make([]Package, len(packages))
	copy(sorted, packages)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].FanIn != sorted[j].FanIn {
			return sorted[i].FanIn > sorted[j].FanIn
		}
		return sorted[i].Depth < sorted[j].Depth
	})

	var selected []Package
	used := 0
	for i := range sorted {
		section := renderPackage(&sorted[i])
		lines := countLines(section) + 1 // +1 for the blank line before section
		if used+lines > maxLines {
			continue
		}
		selected = append(selected, sorted[i])
		used += lines
	}
	return selected
}

// CalculateFanIn computes fan-in for each package by counting how many project
// .go files import that package. It modifies sm.Packages in place.
func CalculateFanIn(projectDir string, sm *SignatureMap) error {
	// Build a map from package path to index for quick lookup.
	pkgIndex := make(map[string]int, len(sm.Packages))
	for i, pkg := range sm.Packages {
		fullPath := sm.ModulePath + "/" + pkg.Path
		pkgIndex[fullPath] = i
	}

	fset := token.NewFileSet()
	return filepath.WalkDir(projectDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// Skip vendor and hidden directories.
		if d.IsDir() {
			name := d.Name()
			if name == "vendor" || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}
		// Process only non-test .go files.
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		f, parseErr := parser.ParseFile(fset, path, nil, parser.ImportsOnly)
		if parseErr != nil {
			return nil // skip unparseable files silently
		}
		for _, imp := range f.Imports {
			importPath := strings.Trim(imp.Path.Value, `"`)
			if idx, ok := pkgIndex[importPath]; ok {
				sm.Packages[idx].FanIn++
			}
		}
		return nil
	})
}
